### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by vickyliao92** [GerkeLab/fcds#79]
Trying to install in R 3.6.1, but received error message: 

> # install.packages("devtools")
> library(processx)
> devtools::install_github("GerkeLab/fcds")
Downloading GitHub repo GerkeLab/fcds@master
Error: Failed to install 'fcds' from GitHub:
  Command not found @win/processx.c:977

**Comment by gadenbuie** [comment]
Hi @vickliao92, I have the strong suspicion that the issue you're seeing is the result of R or your R library being installed to a network path rather than on your machine's hard drive.

I think that if you run

```r
Sys.getenv("R_HOME")
Sys.getenv("R_LIBS_USER")
```

you'll see at least one path that starts with something other than `C:\`. Having R or the R libraries installed on a network drive seems to cause issues with certain configurations of `devtools` and its underlying packages. If this is the case, you may need to follow up with the IT department to have R installed locally on your machine.

**Comment by gadenbuie** [comment]
This was definitely an issue with R and/or the package library being installed on a network drive
